name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20.11'

      - name: Install dependencies
        run: npm install

      - name: Create environment file
        run: |
          echo "export const environment = {" > src/environments/environment.ts
          echo "  apiKey: '${{ secrets.API_KEY }}'," >> src/environments/environment.ts
          echo "  apiKey: '${{ secrets.FIRE_API_KEY }}'," >> src/environments/environment.ts
          echo "  apiKey: '${{ secrets.AUTH_DOMAIN }}'," >> src/environments/environment.ts
          echo "  apiKey: '${{ secrets.PROJECT_ID }}'," >> src/environments/environment.ts
          echo "  apiKey: '${{ secrets.STORAGE_BUCKET }}'," >> src/environments/environment.ts
          echo "  apiKey: '${{ secrets.MESSAGING_SENDER_ID }}'," >> src/environments/environment.ts
          echo "  apiKey: '${{ secrets.APP_ID }}'," >> src/environments/environment.ts
          echo "  apiKey: '${{ secrets.MEASUREMENT_ID }}'," >> src/environments/environment.ts
          echo "};" >> src/environments/environment.ts

      - name: Build project
        run: |
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: dist